drop table if exists users cascade;

create table if not exists users (
user_id bigint not null generated by default as identity primary key,
last_name varchar(100) not null,
first_name varchar(100) not null,
patronymic varchar(100),
email varchar(320) UNIQUE not null,
passport_series varchar(4) not null,
passport_number varchar(6) not null,
passport_issued varchar(320) not null,
passport_date timestamp without time zone not null,
passport_kp varchar(6) not null
);




